# Generated by Django 3.1.5 on 2021-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(max_length=1000, unique=True)),
                ('short', models.CharField(max_length=25, unique=True)),
                ('time', models.CharField(default='-', max_length=2000)),
            ],
        ),
    ]
