# Generated by Django 3.1.5 on 2021-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210125_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
