# Generated by Django 3.1.5 on 2021-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210125_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='combinations',
            field=models.IntegerField(default=100000, unique=True),
        ),
    ]
