# Generated by Django 3.1.5 on 2021-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_url_combinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='combinations',
            field=models.IntegerField(default=100000),
        ),
    ]
