# Generated by Django 3.1.5 on 2021-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_youtubedownloader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('episode', models.IntegerField(default='-')),
                ('time', models.CharField(default='-', max_length=200, unique=True)),
                ('bitrate', models.IntegerField(default='--')),
            ],
        ),
    ]
