# Generated by Django 3.1.5 on 2021-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrate',
            name='size',
            field=models.CharField(max_length=6),
        ),
    ]
