# Generated by Django 3.1.5 on 2021-01-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210129_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrate',
            name='bitrate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitrate',
            name='episode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitrate',
            name='hour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitrate',
            name='minute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitrate',
            name='second',
            field=models.CharField(max_length=100),
        ),
    ]
