# Generated by Django 3.1.5 on 2021-01-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210129_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitrate',
            old_name='second',
            new_name='seconds',
        ),
    ]
