# Generated by Django 3.1.4 on 2020-12-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long", models.CharField(max_length=1000, unique=True)),
                ("short", models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
