# Generated by Django 3.1.4 on 2020-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UrlShortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="time",
            field=models.CharField(default="-", max_length=2000),
        ),
    ]
